### ISSUE TITLE
dive bridge btp --chainA icon --chainB eth fails due to EOF

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#100]
After https://github.com/HugoByte/DIVE/issues/98, I tried running again and got the following error

❯ dive bridge btp --chainA icon --chainB eth
_______\ "Execution in progress"  total_steps:190  current_step_number:128%

❯ dive bridge btp --chainA icon --chainB eth
FATA[2023-08-08 20:19:21] Starlark Run Failed : interpretation_error:{error_message:"Error in cloning git repository 'https://github.com/hugobyte/dive.git' to '/kurtosis-data/tmp-startosis-packages/tmp-repo-dir-607932188/hugobyte/dive'. Make sure that 'https://github.com/hugobyte/dive.git' exists and is a public repository."}

stack trace:

INFO[2023-08-09T00:18:10Z][startosis_runner.go:func1] Executing Starlark package 'DEFAULT_PACKAGE_ID_FOR_SCRIPT' with the following parameters: dry-run: 'false', parallelism: '4', experimental features: '', main function name: '', params: '{"service_name": "prelaunch-data-generator-cl-validator-keystore", "uuid": "a9d68315ac9f40d6905cf9e8f8cefe70"}' 
DEBU[2023-08-09T00:18:10Z][startosis_interpreter.go:Interpret] Interpreting package 'DEFAULT_PACKAGE_ID_FOR_SCRIPT' with contents '
def run(plan, args):
        plan.stop_service(name=args["service_name"])
        plan.print(args["uuid"]) # we add this print of a random UUID to make sure the single stop_service above won't get cached
' and params '{"service_name": "prelaunch-data-generator-cl-validator-keystore", "uuid": "a9d68315ac9f40d6905cf9e8f8cefe70"}' 
DEBU[2023-08-09T00:18:10Z][startosis_interpreter.go:Interpret] Successfully interpreted Starlark code into 0 instructions 
DEBU[2023-08-09T00:18:10Z][api_container_service.go:runStarlark] Received response line from Starlark runner: 'progress_info:{current_step_info:"Interpreting Starlark code - execution will begin shortly"}' 
WARN[2023-08-09T00:18:10Z][startosis_interpreter.go:Interpret] Using args dictionary as parameter is deprecated. Consider unpacking the dictionary into individual parameters. For example: run(plan, args) to run(plan, param1, param2, ...) 
DEBU[2023-08-09T00:18:10Z][kurtosis_plan_instruction.go:func1] Marking the plan as invalid as instruction 'stop_service(name="prelaunch-data-generator-cl-validator-keystore")' had the following resolution status: 'InstructionIsNotResolvableAbort' 
DEBU[2023-08-09T00:18:10Z][startosis_interpreter.go:InterpretAndOptimizePlan] First interpretation of package generated 2 instructions 
DEBU[2023-08-09T00:18:10Z][startosis_interpreter.go:InterpretAndOptimizePlan] Current enclave state contains 137 instructions 
DEBU[2023-08-09T00:18:10Z][startosis_interpreter.go:InterpretAndOptimizePlan] Starting iterations to find the best plan to execute given the current state of the enclave 
DEBU[2023-08-09T00:18:10Z][startosis_interpreter.go:InterpretAndOptimizePlan] Exhausted all possibilities. Concatenated the previous enclave plan with the new plan to obtain a 139 instructions plan 
DEBU[2023-08-09T00:18:10Z][startosis_runner.go:func1] Successfully interpreted Starlark script into a series of 139 Kurtosis instructions 
DEBU[2023-08-09T00:18:10Z][api_container_service.go:runStarlark] Received response line from Starlark runner: 'progress_info:{current_step_info:"Starting validation"  total_steps:139}' 
DEBU[2023-08-09T00:18:10Z][startosis_runner.go:forwardKurtosisResponseLineChannelUntilSourceIsClosed] Received kurtosis execution line Kurtosis:
progress_info:{current_step_info:"Validating Starlark code and downloading container images - execution will begin shortly"} 
DEBU[2023-08-09T00:18:10Z][api_container_service.go:runStarlark] Received response line from Starlark runner: 'progress_info:{current_step_info:"Validating Starlark code and downloading container images - execution will begin shortly"}' 
DEBU[2023-08-09T00:18:12Z][startosis_validator.go:func1] Finished validating environment. Validating and downloading container images. 
DEBU[2023-08-09T00:18:12Z][startosis_validator.go:func1] Errors encountered downloading and validating container images. 
DEBU[2023-08-09T00:18:12Z][startosis_runner.go:forwardKurtosisResponseLineChannelUntilSourceIsClosed] Received kurtosis execution line Kurtosis:
error:{validation_error:{error_message:"Error while validating instruction stop_service(name=\"prelaunch-data-generator-cl-validator-keystore\"). The instruction can be found at DEFAULT_PACKAGE_ID_FOR_SCRIPT[3:19]\n\tCaused by: There was an error validating 'stop_service' as service name 'prelaunch-data-generator-cl-validator-keystore' doesn't exist"}} 
DEBU[2023-08-09T00:18:12Z][startosis_runner.go:forwardKurtosisResponseLineChannelUntilSourceIsClosed] Received kurtosis execution line Kurtosis:
run_finished_event:{} 
DEBU[2023-08-09T00:18:12Z][api_container_service.go:runStarlark] Received response line from Starlark runner: 'error:{validation_error:{error_message:"Error while validating instruction stop_service(name=\"prelaunch-data-generator-cl-validator-keystore\"). The instruction can be found at DEFAULT_PACKAGE_ID_FOR_SCRIPT[3:19]\n\tCaused by: There was an error validating 'stop_service' as service name 'prelaunch-data-generator-cl-validator-keystore' doesn't exist"}}' 
DEBU[2023-08-09T00:18:12Z][api_container_service.go:runStarlark] Received response line from Starlark runner: 'run_finished_event:{}' 
DEBU[2023-08-09T00:18:12Z][startosis_runner.go:forwardKurtosisResponseLineChannelUntilSourceIsClosed] Kurtosis instructions stream was closed. Exiting execution loop. Run finished: 'true' 
WARN[2023-08-09T00:18:12Z][startosis_runner.go:func1] An error occurred validating the sequence of Kurtosis instructions. See logs above for more details 
INFO[2023-08-09T00:18:12Z][api_container_service.go:runStarlark] Startosis script execution returned, no more output to stream. 
ERRO[2023-08-09T00:19:20Z][git_package_content_provider.go:atomicClone] Error cloning git repository: 'https://github.com/hugobyte/dive.git' to '/kurtosis-data/tmp-startosis-packages/tmp-repo-dir-607932188/hugobyte/dive'. Error was: 
unexpected EOF

**Comment by shreyasbhat0** [comment]
@CyrusVorwald  Can this be closed ? . Still this issues exist?

**Comment by CyrusVorwald** [comment]
I am not sure, I haven't been able to replicate. There are some flaky issues though. Can close and re-open if it pops up.
