### ISSUE TITLE
Example services.json in readme is of 2 icon chains but the command is of icon and eth

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#103]
At https://github.com/HugoByte/DIVE#setting-bridge-between-two-chains, the example json does not match the command

**Comment by Mr-Nobody21** [comment]
@CyrusVorwald 

Fixed :-
https://github.com/HugoByte/DIVE/blob/main/README.md#setting-up-bridge-between-two-chains-which-is-already-running
