### ISSUE TITLE
height of mangata parachain is zero when running in mainnet

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/DIVE#128]
## Overview
height of mangata parachain is zero when running in testnet

## Steps to Reproduce
1. run mangata parachain in testnet
2. command: ./dive chain kusama -p mangata -n mainnet

## Expected Behavior
height of the blocks should be incrementing

## Actual Behavior
no increment in block height

**Comment by hemz10** [comment]
issue is still reproducible 
![image](https://github.com/HugoByte/DIVE/assets/96766939/fb23d748-6fe4-4220-8c3e-25d03b7f234a)

**Comment by hemz10** [comment]
verified and closing this issue as fixed
