### ISSUE TITLE
ibc relay stops when running bridge command between 2 archway chains in linux 

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#128]
## Overview
Relay doesn't work when running bridge between in 2 archway chains

## Steps to Reproduce
1. run dive bridge ibc --chainA archway --chainB archway
2. observe the logs in ibc relay. no logs are recorded and relay is stopped

## Expected Behavior
relay should run

## Device Information

**Desktop (please complete the following information):**
 - OS: linux
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
UBUNTU_CODENAME=jammy

**Comment by shanithkk** [comment]
fixed issue on #136
issue is due to rly binary architecture
