### ISSUE TITLE
Successful message output even when unknown chain type is given for ibc bridge

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#129]
## Overview
chainA or chainB is unknown chain type is given we are still getting an output that dive.json is generated. 

## Steps to Reproduce
1. run dive bridge ibc --chainA archway --chainB invalid_chain
2. Observe we are getting successful message. 

## Expected Behavior
Should validate chain name initially and should fail if invalid chain type is given

**Comment by shreyasbhat0** [comment]
https://github.com/HugoByte/DIVE/pull/146 fixes this issues

**Comment by hemz10** [comment]
Closing this issue as fixed. 
Current implementation supports only archway for ibc
![image](https://github.com/HugoByte/DIVE/assets/96766939/97b37e12-e3b4-4209-94df-3ed26955641c)
