### ISSUE TITLE
Typo error in archway node successful output

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#130]
## Overview
Typo error in output 

## Steps to Reproduce
1. run dive chain archway
2. Observe the output

## Expected Behavior
No typo error

## Screenshots
![image](https://github.com/HugoByte/DIVE/assets/96766939/85ba0915-549b-4d49-bb6e-ef3f641e5b56)

**Comment by shreyasbhat0** [comment]
https://github.com/HugoByte/DIVE/pull/146 fixes this issues

**Comment by hemz10** [comment]
closing this issue as fixed
