### ISSUE TITLE
Fatal error on running chain command twice - archway

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#131]
## Overview
running dive chain archway command second time gives fatal error

## Steps to Reproduce
1. run dive chain archway
2. run dive chain archway again
3. Observe we are getting fatal error

## Expected Behavior
It should output that chain is already running

**Comment by shreyasbhat0** [comment]
https://github.com/HugoByte/DIVE/pull/146 fixes this issues

**Comment by hemz10** [comment]
closing this issue as fixed
