### ISSUE TITLE
explorer is not working for pendulum parachain in testnet and localnet

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/DIVE#159]
## Overview
explorer is not working for pendulum parachain in testnet and localnet

## Steps to Reproduce
1. run dive chain polkadot -p pendulum -n testnet --explorer and run dive chain polkadot -p pendulum --explorer --metrics
2. Try to open explorer with pendulum endpoint

## Expected Behavior
Explorer to give details

**Comment by sindhu0820** [comment]
for testnet, explorer is working

**Comment by hemz10** [comment]
explorer is working for localnet as well and closing this issue as fixed
