### ISSUE TITLE
Neutron node is not starting after running archway node

### ISSUE THREAD

**Issue by Prathiksha-Nataraja** [HugoByte/DIVE#159]
## Overview
After starting the archway node, if we try to start neutron node without cleaning the enclave neutron node is not starting.

## Steps to Reproduce
1. run archway chain
2. run neutron chain

## Expected Behavior
1.  Archway node is  started
2.  Neutron node is started

## Screenshots
<img width="955" alt="Screenshot 2023-09-08 at 11 30 01 AM" src="https://github.com/HugoByte/DIVE/assets/90592522/7b161fc9-ac51-46ac-8b39-8fdc4c5a10b3">

**Comment by Mr-Nobody21** [comment]
https://github.com/HugoByte/DIVE/pull/182

Will be fixed in next release
