### ISSUE TITLE
Improve installation steps

### ISSUE THREAD

**Issue by FidelVe** [HugoByte/DIVE#204]
## Overview
Hello team.

Instead of a bug this is a recommendation to make the installation steps easier to allow for less friction for developers during installation:

1. the installation steps for Linux currently say the following:
```
curl -L https://github.com/HugoByte/DIVE/releases/download/{latest-version}/dive-cli_{latest-version}_linux_{arch}.tar.gz
```
It would be better experience for developers if a valid live link of the latest release is provided in this step or put a note at the end with a link to the release page to make it clear for developers where they can find the latest release.

2. On my machine the `curl` command throws the following error:
```
$ curl -L https://github.com/HugoByte/DIVE/releases/download/v0.0.13-beta/dive-cli_v0.0.13-beta_linux_amd64.tar.gz
curl: (3) URL using bad/illegal format or missing URL
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

To fix this you can change the command to use the `--output` flag with curl:

```
curl -L --output dive.tar.gz https://github.com/HugoByte/DIVE/releases/download/v0.0.13-beta/dive-cli_v0.0.13-beta_linux_amd64.tar.gz
```
Add the following line at the end of the installation process to verify that the installation process was correct:

```
$ dive version
CLI version - v0.0.13-beta
```

**Comment by shreyasbhat0** [comment]
@FidelVe thanks for notifying this . We will fix this in documentation soon

**Comment by shreyasbhat0** [comment]
Dive installation steps for Linux is  updated in the readme.
