### ISSUE TITLE
No such image: ethpandaops/ethereum-genesis-generator:1.3.1

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#22]
## Overview
Ethereum node fails to build.

## Steps to Reproduce
❯ kurtosis run . '{"action":"setup_relay","relay":{"name":"btp","links": {"src": "icon", "dst": "eth"},"bridge":"false"}}' --enclave btp

## Device Information

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.2.1

## Additional Context

> add_service name="prelaunch-data-generator-1688142883168067631" config=ServiceConfig(image="ethpandaops/ethereum-genesis-generator:1.3.1", files={}, entrypoint=["sleep", "999999"])
There was an error executing Starlark code
An error occurred executing instruction (number 12) at github.com/kurtosis-tech/eth-network-package/src/prelaunch_data_generator/prelaunch_data_generator_launcher/prelaunch_data_generator_launcher.star[21:18]:
  add_service(name="prelaunch-data-generator-1688142883168067631", config=ServiceConfig(image="ethpandaops/ethereum-genesis-generator:1.3.1", files={}, entrypoint=["sleep", "999999"]))
  Caused by: Unexpected error occurred starting service 'prelaunch-data-generator-1688142883168067631'
  Caused by: An error occurred starting the user service container for user service with UUID '8e91d5769986460386535245a2bc2a6b'
  Caused by: Could not create Docker container 'prelaunch-data-generator-1688142883168067631--8e91d5769986460386535245a2bc2a6b' from image 'ethpandaops/ethereum-genesis-generator:1.3.1'
  Caused by: Error response from daemon: No such image: ethpandaops/ethereum-genesis-generator:1.3.1

Error encountered running Starlark code.

**Comment by shreyasbhat0** [comment]
Hey @CyrusVorwald  , this issues which you're facing is because of docker image . For now the work around for this would be pulling amd64 version of image by running 
```
docker pull ethpandaops/ethereum-genesis-generator:1.3.1 --platform linux/amd64
```
 and run the  command 
```
kurtosis run . '{"action":"setup_relay","relay":{"name":"btp","links": {"src": "icon", "dst": "eth"},"bridge":"false"}}' --enclave btp
```
