### ISSUE TITLE
Command to run two nodes and a relay fails on second run

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#23]
## Overview
Attempts to provision for same node twice

## Steps to Reproduce
Run `❯ kurtosis run . '{"action":"setup_relay","relay":{"name":"btp","links": {"src": "icon", "dst": "eth"},"bridge":"false"}}' --enclave btp` twice

## Expected Behavior
Should either only attempt to provision if node is not already running, or provision new nodes.

## Device Information

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version 12.2.1

## Additional Context

There was an error validating Starlark code
Error while validating instruction upload_files(src="github.com/hugobyte/chain-package/services/jvm/icon/static-files/config/", name="config-files-0"). The instruction can be found at github.com/hugobyte/chain-package/services/jvm/icon/src/node-setup/start_icon_node.star[29:22]
	Caused by: There was an error validating 'upload_files' as artifact name 'config-files-0' already exists
There was an error validating Starlark code
Error while validating instruction upload_files(src="github.com/hugobyte/chain-package/services/jvm/icon/static-files/contracts/", name="contracts-0"). The instruction can be found at github.com/hugobyte/chain-package/services/jvm/icon/src/node-setup/start_icon_node.star[30:22]
	Caused by: There was an error validating 'upload_files' as artifact name 'contracts-0' already exists
There was an error validating Starlark code
Error while validating instruction add_service(name="icon-node-0", config=ServiceConfig(image="iconloop/goloop-icon:v1.3.5", ports={"rpc": PortSpec(number=9080, transport_protocol="TCP", application_protocol="http")}, public_ports={"rpc": PortSpec(number=8090, transport_protocol="TCP", application_protocol="http")}, files={"/goloop/config/": "config-files-0", "/goloop/contracts/": "contracts-0"}, cmd=["/bin/sh", "-c", "/goloop/config/start-icon-0.sh"], env_vars={"GOLOOP_LOG_LEVEL": "trace", "GOLOOP_P2P": ":8080", "GOLOOP_P2P_LISTEN": ":7080", "GOLOOP_RPC_ADDR": ":9080", "ICON_CONFIG": "/goloop/config/icon_config.json"})). The instruction can be found at github.com/hugobyte/chain-package/services/jvm/icon/src/node-setup/start_icon_node.star[55:50]
	Caused by: There was an error validating 'add_service' as service 'icon-node-0' already exists

Error encountered running Starlark code.

**Comment by hemz10** [comment]
Hi @CyrusVorwald , 
Running the same command twice without cleaning the kurtosis engine will result in this error. Currently the implementation is to manually clean the kurtosis before executing `kurtosis run ..` command. 
But this will be automated in next release with cli integration where kurtosis clean will execute before running kurtosis run.

**Comment by CyrusVorwald** [comment]
Understood, thanks
