### ISSUE TITLE
Running eth as a single node fails

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#24]
❯ kurtosis run github.com/hugobyte/dive '{"action":"start_node","node_name":"eth"}' --enclave btp

There was an error interpreting Starlark code
Cloning the package 'https://github.com/hugobyte/dive.git' failed. An error occurred while moving package at temporary destination '/kurtosis-data/tmp-startosis-packages/tmp-repo-dir-1583757467/hugobyte/dive' to final destination '/kurtosis-data/startosis-packages/hugobyte/dive'

**Comment by shreyasbhat0** [comment]
Did you run the same command before ? if yes , Run 
```
kurtosis clean -a
```
and run the command 

```
kurtosis run github.com/hugobyte/dive '{"action":"start_node","node_name":"eth"}' --enclave btp
```

**Comment by CyrusVorwald** [comment]
That was it, closing this issue. Thank you.
