### ISSUE TITLE
invalid url opens when explorer is true in config

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#244]
## Overview
invalid url opens when explorer is true in config
P.S: Running kurtosis on cloud

## Steps to Reproduce
1. run dive chain polkadot -c ./sample-jsons/polkadot_config.json 
2. See url - `http://127.0.0.1/?rpc=ws://127.0.0.1:32690#/explorer`

config: 
```json
{
  "chain_type": "testnet",
  "relaychain": {
  },

  "parachains": [
    {
      "name":"polkadex",
      "nodes": [
        {
          "name": "alice",
          "node_type": "collator",
          "prometheus": false

        },
        {
          "name": "bob",
          "node_type": "full",
          "prometheus": false
        }
      ]
    }
  ],
  "explorer": true
}
```

## Expected Behavior
valid explorer url to be opened

**Comment by Mr-Nobody21** [comment]
Fixed in pr #353

**Comment by abhiyana** [comment]
@hemz10 , Hi! The explorer will no longer open automatically when running in kurtosis cloud. Please confirm the changes made and let us know for any other issues.

**Comment by hemz10** [comment]
Hi @abhiyana As per the current changes, it works as expected, and Explorer doesn't open when running in the cloud. Hopefully, this feature will be enabled once we have fixed the Explorer issue. This issue will be closed here and will be tracked in explorer issue itself.
