### ISSUE TITLE
Deploying contract fails

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#25]
Running
> `kurtosis clean -a`
> `kurtosis run github.com/hugobyte/dive '{"action":"setup_relay","relay":{"name":"btp","links": {"src": "icon", "dst": "eth"},"bridge":"false"}}' --enclave btp`

fails with

> exec service_name="icon-node-0" recipe=ExecRecipe(command=["./bin/goloop", "rpc", "sendtx", "deploy", "contracts/bmc.jar", "--content_type", "application/java", "--params", "{\"_net\":\"{{kurtosis:89367721f9364b09a2861bb060799655:output.runtime_value}}.icon\"}", "--key_store", "keystores/keystore.json", "--key_password", "gochain", "--step_limit", "500000000000", "--uri", "http://{{kurtosis:9aa431253270488cb396e0c0d9d60ac5:ip_address.runtime_value}}:9080/api/v3/icon_dex", "--nid", "{{kurtosis:89367721f9364b09a2861bb060799655:output.runtime_value}}"])

There was an error executing Starlark code
An error occurred executing instruction (number 129) at github.com/hugobyte/dive/services/jvm/icon/src/node-setup/contract_deploy.star[40:23]:
  wait(service_name="icon-node-0", recipe=PostHttpRequestRecipe(port_id="rpc", endpoint="/api/v3/icon_dex", body="{ \"jsonrpc\": \"2.0\", \"method\": \"icx_getTransactionResult\", \"id\": 1, \"params\": { \"txHash\": {{kurtosis:1bfc4c2a34ac49eb908a1b0bb59e4342:output.runtime_value}} } }", content_type="application/json", extract={"score_address": ".result.scoreAddress"}), field="code", assertion="==", target_value=200)
  Caused by: An error occurred checking if service 'icon-node-0' is ready.
  Caused by: Recipe execution timed-out waiting for the recipe execution to become valid on service 'icon-node-0'. Tried '10' times. Last recipe execution error was:
   '$An error occurred when running HTTP request recipe 'PostHttpRequestRecipe(port_id="rpc", endpoint="/api/v3/icon_dex", body="{ \"jsonrpc\": \"2.0\", \"method\": \"icx_getTransactionResult\", \"id\": 1, \"params\": { \"txHash\": {{kurtosis:1bfc4c2a34ac49eb908a1b0bb59e4342:output.runtime_value}} } }", content_type="application/json", extract={"score_address": ".result.scoreAddress"})'
  Caused by: An error occurred while running extractors from HTTP recipe
  Caused by: An error occurred running extractor '.result.scoreAddress' on recipe
  Caused by: No field '.result.scoreAddress' was found on input '{"jsonrpc":"2.0","error":{"code":-31003,"message":"Executing: Executing"},"id":1}
  '
   --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/extractor.go:44 (extract) ---'

Error encountered running Starlark code.

**Comment by shreyasbhat0** [comment]
Time out issue from the node , will be fixed in future release
