### ISSUE TITLE
bridge between neutron and neutron fails

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#350]
## Overview
Scenario - should start bridge between neutron and neutron by running one custom neutron chain

## Steps to Reproduce
1. dive chain neutron       
2. dive chain neutron -c <path to config>
3.  dive bridge ibc --chainA neutron --chainB neutron --chainAServiceName neutron-node-test-chain1 --chainBServiceName test-chain1

## Expected Behavior
Bridge to be created between neutron and neutron

## Screenshots
![image](https://github.com/HugoByte/DIVE/assets/96766939/3cb388ce-e9e6-46a6-a9f1-4a7b1ce91312)

**Comment by riyasng12** [comment]
@hemz10 , Hey! The chainB service came provided seems to be wrong. The actual service name should be `neutron-node-test-chain3` instead of test-chain1. Please try again with the given command:

```
dive bridge ibc --chainA neutron --chainB neutron --chainAServiceName neutron-node-test-chain1 --chainBServiceName neutron-node-test-chain3
```

**Comment by hemz10** [comment]
Yes it failed due to an error in wrong service name, works as expected with right service name so hence closing this issue as completed
