### ISSUE TITLE
kusama relaychain is not returing any block details in explorer

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/DIVE#45]
## Overview
kusama relaychain is not returing any block details with endpoints returned by dive

## Steps to Reproduce
1. run an kusama relaychain
2. once when the chain is running successfully try to get the block details in polkadot.js

## Expected Behavior
should get the block details

## Actual Behavior
but not getting block details

## Screenshots
![Screenshot (70)](https://github.com/HugoByte/dive-core/assets/149460495/dd40756b-6425-4cbc-b8df-70779feeeb36)

**Comment by sindhu0820** [comment]
when endpoint , which is present in service details is given to local host , the explorer is not working

**Comment by hemz10** [comment]
New implementation which opens explorer by default works but it doesn't open an valid port

**Comment by hemz10** [comment]
verified and closing this issue as fixed
