### ISSUE TITLE
Fatal error on running chain that is already running

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#58]
## Overview
Running a chain that is already running should give a proper error message that chain is already running but it returns fatal error

## Steps to Reproduce
1. Run Any chain (icon, eth or hardhat)
2. Run the same chain again
3. Fatal error is thrown

## Expected Behavior
Should give an proper output that chain is already running 

## Screenshots
![image](https://github.com/HugoByte/DIVE/assets/96766939/2b87601c-cfc3-456a-beba-410694f34838)

**Comment by Mr-Nobody21** [comment]
#57 will be fixed when this pr is merged to main

**Comment by hemz10** [comment]
Closing this issue as fixed.
