### ISSUE TITLE
Spinner logs and fatal error are both printed together

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#60]
## Overview
In some of the scenarios both Spinner logs and fatal error are both printed together

## Steps to Reproduce
1. Stop Kurtosis engine if running in the background
2. Try to run any chain
3. Observe the output

## Expected Behavior
Expected only fatal error to be printed

## Screenshots
![image](https://github.com/HugoByte/DIVE/assets/96766939/79513dec-33f4-4354-bcfb-b7735fb0fe05)

**Comment by shreyasbhat0** [comment]
This issue will be fixed when https://github.com/HugoByte/DIVE/pull/57 pr is merged to main

**Comment by hemz10** [comment]
Closing this issue as fixed.
