### ISSUE TITLE
Icon node started output on passing genesis file that doesn't exist

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#62]
## Overview
Running icon chain by giving custom config and genesis file that doesn't exist gives successfull output

## Steps to Reproduce
1. run icon chain by giving custom config and genesis that doesn't exist
2. Observe that output says Icon node is started 

## Expected Behavior
Expected error output

**Comment by shreyasbhat0** [comment]
This issue will be fixed when https://github.com/HugoByte/DIVE/pull/57 pr is merged to main

**Comment by hemz10** [comment]
Closing this issue as fixed
