### ISSUE TITLE
error running parallel parachain in mainnet

### ISSUE THREAD

**Issue by sindhu0820** [HugoByte/DIVE#73]
## Overview
error running parallel parachain in mainnet and testnet

## Steps to Reproduce
1. run parallel parachain in mainnet

## Expected Behavior
parallel parachain should start running

## Actual Behavior
parallel parachain is not running

## Screenshots
![Screenshot (96)](https://github.com/HugoByte/dive-core/assets/149460495/a9be5a9c-778a-4d63-9ee4-89307f28e3d3)

**Comment by hemz10** [comment]
blocks are not produced for mainnet

**Comment by hemz10** [comment]
Also please find the typo here, parachain is a single word
![image](https://github.com/HugoByte/dive-core/assets/96766939/2ae4b581-bc38-491c-9078-86b6960018ce)

**Comment by sindhu0820** [comment]
verified the issue and closing the bug as fixed

**Comment by sindhu0820** [comment]
for reference:
![image](https://github.com/HugoByte/dive-core/assets/149460495/71310f4e-86d7-4b08-83a7-331de37c0dd9)

**Comment by hemz10** [comment]
Hi @riyasng12 we have now best being shown in the logs, what about finalized ? 
![image](https://github.com/HugoByte/DIVE/assets/96766939/8da16a08-3d68-4848-bbfe-69b9be7cbbd7)

**Comment by riyasng12** [comment]
@hemz10 , until the relaychain fetches the block at which the parachain is registered, the parachain will not show the finalized block

**Comment by hemz10** [comment]
As per above comments closing this issue as fixed
