### ISSUE TITLE
Add verbose output

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#76]
Currently, the only information that is displayed is `_/______ "Execution in progress"  total_steps:X  current_step_number:Y`. While this is good and in accordance with Linux's [rule of silence](http://www.linfo.org/rule_of_silence.html), there should be an option, such as `--verbose` to standard output and/or standard error.

**Comment by shreyasbhat0** [comment]
Verbose flag is added  in the latest [release](https://github.com/HugoByte/DIVE/releases/tag/v0.0.3-beta)
