### ISSUE TITLE
dive clean doesn't remove service.json

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#88]
## Overview
Run any chain which generates service.json and do clean, it doesn't remove service.json

## Steps to Reproduce
1. run any chain
2. run dive clean
3. observe service.json is not removed

## Expected Behavior
Clean should remove service.json

**Comment by shreyasbhat0** [comment]
This issue is fixed in the latest [release](https://github.com/HugoByte/DIVE/releases/tag/v0.0.3-beta)
