### ISSUE TITLE
Typo error in output file 

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#90]
## Overview
Output of dive chain icon command is grammatically incorrect

## Steps to Reproduce
1. Run dive chain icon -d command
2. Observe the output

## Expected Behavior
Valid output message

## Additional Context
Output is  : "Icon Node Started. Please find service details in current working directory(services.json) **in current working directory**"

**Comment by shreyasbhat0** [comment]
This issue is fixed in the latest [release](https://github.com/HugoByte/DIVE/releases/tag/v0.0.3-beta)
