### ISSUE TITLE
nil pointer dereference issue on bridge between custom icon config1 and any chain 

### ISSUE THREAD

**Issue by hemz10** [HugoByte/DIVE#95]
## Overview
Running custom icon chain with genesis1 and creating bridge between them fails.

## Steps to Reproduce
1. run dive chain icon -c config1.json -g genesis-icon-1.zip -d 
2. run dive chain eth
3. run dive bridge btp --chainA icon --chainB eth
4. observe it fails with nil pointer dereference

## Expected Behavior
to start bridge between 2 chains.

**Comment by Mr-Nobody21** [comment]
https://github.com/HugoByte/DIVE/releases/tag/v0.0.5-beta
