### ISSUE TITLE
dive bridge btp --chainA icon --chainB eth fails at step 128 with no output

### ISSUE THREAD

**Issue by CyrusVorwald** [HugoByte/DIVE#99]
❯ dive clean
INFO[2023-08-08 20:10:22] Successfully connected to kurtosis engine...
INFO[2023-08-08 20:10:22] Initializing cleaning process...
INFO[2023-08-08 20:10:24] Successfully destroyed and cleaned enclave dive

❯ dive bridge btp --chainA icon --chainB eth
_______\ "Execution in progress"  total_steps:190  current_step_number:128%

stack trace

DEBU[2023-08-09T00:17:54Z][extractor.go:extract] Running extractor against query '{"jsonrpc":"2.0","error":{"code":-31003,"message":"Executing: Executing"},"id":1}
' and input '.result.scoreAddress' 
DEBU[2023-08-09T00:17:54Z][extractor.go:extract] Found match '<nil>'                          
DEBU[2023-08-09T00:17:56Z][startosis_runner.go:forwardKurtosisResponseLineChannelUntilSourceIsClosed] Received kurtosis execution line Kurtosis:
error:{execution_error:{error_message:"An error occurred executing instruction (number 128) at github.com/hugobyte/dive/services/jvm/icon/src/node-setup/contract_deploy.star[41:23]:\nwait(service_name=\"icon-node-0\", recipe=PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:beea38dd67634f66aec6e8882dcb9b90:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"}), field=\"code\", assertion=\"==\", target_value=200)\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/startosis_executor.go:130 (sendErrorAndFail) ---\nCaused by: An error occurred checking if service 'icon-node-0' is ready.\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/kurtosis_instruction/wait/wait.go:257 (WaitCapabilities.Execute) ---\nCaused by: Recipe execution timed-out waiting for the recipe execution to become valid on service 'icon-node-0'. Tried '10' times. Last recipe execution error was:\n '$An error occurred when running HTTP request recipe 'PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:beea38dd67634f66aec6e8882dcb9b90:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"})'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/post_http_request_recipe.go:175 (PostHttpRequestRecipe.Execute) ---\nCaused by: An error occurred while running extractors from HTTP recipe\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/http_request_recipe.go:95 (executeInternal) ---\nCaused by: An error occurred running extractor '.result.scoreAddress' on recipe\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/extractor.go:90 (runExtractors) ---\nCaused by: No field '.result.scoreAddress' was found on input '{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-31003,\"message\":\"Executing: Executing\"},\"id\":1}\n'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/extractor.go:44 (extract) ---'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/kurtosis_instruction/shared_helpers/service_helpers.go:111 (executeServiceAssertionWithRecipeWithTicker) ---"}} 
DEBU[2023-08-09T00:17:56Z][api_container_service.go:runStarlark] Received response line from Starlark runner: 'error:{execution_error:{error_message:"An error occurred executing instruction (number 128) at github.com/hugobyte/dive/services/jvm/icon/src/node-setup/contract_deploy.star[41:23]:\nwait(service_name=\"icon-node-0\", recipe=PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:beea38dd67634f66aec6e8882dcb9b90:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"}), field=\"code\", assertion=\"==\", target_value=200)\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/startosis_executor.go:130 (sendErrorAndFail) ---\nCaused by: An error occurred checking if service 'icon-node-0' is ready.\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/kurtosis_instruction/wait/wait.go:257 (WaitCapabilities.Execute) ---\nCaused by: Recipe execution timed-out waiting for the recipe execution to become valid on service 'icon-node-0'. Tried '10' times. Last recipe execution error was:\n '$An error occurred when running HTTP request recipe 'PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:beea38dd67634f66aec6e8882dcb9b90:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"})'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/post_http_request_recipe.go:175 (PostHttpRequestRecipe.Execute) ---\nCaused by: An error occurred while running extractors from HTTP recipe\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/http_request_recipe.go:95 (executeInternal) ---\nCaused by: An error occurred running extractor '.result.scoreAddress' on recipe\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/extractor.go:90 (runExtractors) ---\nCaused by: No field '.result.scoreAddress' was found on input '{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-31003,\"message\":\"Executing: Executing\"},\"id\":1}\n'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/extractor.go:44 (extract) ---'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/kurtosis_instruction/shared_helpers/service_helpers.go:111 (executeServiceAssertionWithRecipeWithTicker) ---"}}'

**Comment by leeederek** [comment]
+1 to this

I've hit this multiple times with similar errors stemming from `github.com/hugobyte/dive/services/jvm/icon/src/node-setup/contract_deploy.star` as well.

**Comment by shreyasbhat0** [comment]
@CyrusVorwald  and @leeederek  is the issues still persist ?

**Comment by CyrusVorwald** [comment]
Yes.

INFO   [2023-08-17 15:36:14] progress_info:{current_step_info:"Execution in progress" total_steps:191 current_step_number:129}
INFO   [2023-08-17 15:36:14] instruction:{position:{filename:"github.com/hugobyte/dive/services/jvm/icon/src/node-setup/contract_deploy.star" line:41 column:23} instruction_name:"wait" arguments:{serialized_arg_value:"\"icon-node-0xacbc4e\"" arg_name:"service_name"} arguments:{serialized_arg_value:"PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:2a024810869242928178ea3dfc59dbe8:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"})" arg_name:"recipe" is_representative:true} arguments:{serialized_arg_value:"\"code\"" arg_name:"field" is_representative:true} arguments:{serialized_arg_value:"\"==\"" arg_name:"assertion" is_representative:true} arguments:{serialized_arg_value:"200" arg_name:"target_value" is_representative:true} arguments:{} arguments:{} executable_instruction:"wait(service_name=\"icon-node-0xacbc4e\", recipe=PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:2a024810869242928178ea3dfc59dbe8:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"}), field=\"code\", assertion=\"==\", target_value=200)"}
INFO   [2023-08-17 15:36:25] error:{execution_error:{error_message:"An error occurred executing instruction (number 129) at github.com/hugobyte/dive/services/jvm/icon/src/node-setup/contract_deploy.star[41:23]:\nwait(service_name=\"icon-node-0xacbc4e\", recipe=PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:2a024810869242928178ea3dfc59dbe8:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"}), field=\"code\", assertion=\"==\", target_value=200)\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/startosis_executor.go:130 (sendErrorAndFail) ---\nCaused by: An error occurred checking if service 'icon-node-0xacbc4e' is ready.\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/kurtosis_instruction/wait/wait.go:257 (WaitCapabilities.Execute) ---\nCaused by: Recipe execution timed-out waiting for the recipe execution to become valid on service 'icon-node-0xacbc4e'. Tried '11' times. Last recipe execution error was:\n '$An error occurred when running HTTP request recipe 'PostHttpRequestRecipe(port_id=\"rpc\", endpoint=\"/api/v3/icon_dex\", body=\"{ \\\"jsonrpc\\\": \\\"2.0\\\", \\\"method\\\": \\\"icx_getTransactionResult\\\", \\\"id\\\": 1, \\\"params\\\": { \\\"txHash\\\": {{kurtosis:2a024810869242928178ea3dfc59dbe8:output.runtime_value}} } }\", content_type=\"application/json\", extract={\"score_address\": \".result.scoreAddress\"})'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/post_http_request_recipe.go:175 (PostHttpRequestRecipe.Execute) ---\nCaused by: An error occurred when running HTTP request recipe\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/recipe/http_request_recipe.go:76 (executeInternal) ---\nCaused by: An error occurred when getting service 'icon-node-0xacbc4e' for HTTP request\n --- at /home/circleci/project/core/server/api_container/server/service_network/default_service_network.go:604 (DefaultServiceNetwork.HttpRequestService) ---\nCaused by: An error occurred getting service 'b969dd0fbe2d470baa2484cdda4b85cf'\n --- at /home/circleci/project/core/server/api_container/server/service_network/default_service_network.go:645 (DefaultServiceNetwork.GetService) ---\nCaused by: An error occurred getting user services in enclave 'd92bf1eb449f4e97ba5d11f0e8f8c72b' using filters '&{Names:map[] UUIDs:map[b969dd0fbe2d470baa2484cdda4b85cf:true] Statuses:map[]}'\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:278 (MetricsReportingKurtosisBackend.GetUserServices) ---\nCaused by: An error occurred getting user services matching filters '&{Names:map[] UUIDs:map[b969dd0fbe2d470baa2484cdda4b85cf:true] Statuses:map[]}'\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/user_services_functions/get_user_services.go:23 (GetUserServices) ---\nCaused by: An error occurred getting matching user service resources\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/shared_helpers/shared_helpers.go:313 (GetMatchingUserServiceObjsAndDockerResourcesNoMutex) ---\nCaused by: An error occurred getting user service containers in enclave 'd92bf1eb449f4e97ba5d11f0e8f8c72b' by labels: map[com.kurtosistech.app-id:kurtosis com.kurtosistech.container-type:user-service com.kurtosistech.enclave-id:d92bf1eb449f4e97ba5d11f0e8f8c72b]\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/shared_helpers/shared_helpers.go:521 (getMatchingUserServiceDockerResources) ---\nCaused by: An error occurred getting containers with labels '{fields:map[label:map[com.kurtosistech.app-id=kurtosis:true com.kurtosistech.container-type=user-service:true com.kurtosistech.enclave-id=d92bf1eb449f4e97ba5d11f0e8f8c72b:true]]}'\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1111 (DockerManager.GetContainersByLabels) ---\nCaused by: An error occurred getting the docker containers with filter args '{fields:map[label:map[com.kurtosistech.app-id=kurtosis:true com.kurtosistech.container-type=user-service:true com.kurtosistech.enclave-id=d92bf1eb449f4e97ba5d11f0e8f8c72b:true]]}'\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1620 (DockerManager.getContainersByFilterArgs) ---\nCaused by: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.43/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.kurtosistech.app-id%3Dkurtosis%22%3Atrue%2C%22com.kurtosistech.container-type%3Duser-service%22%3Atrue%2C%22com.kurtosistech.enclave-id%3Dd92bf1eb449f4e97ba5d11f0e8f8c72b%22%3Atrue%7D%7D\": context deadline exceeded'\n --- at /home/circleci/project/core/server/api_container/server/startosis_engine/kurtosis_instruction/shared_helpers/service_helpers.go:111 (executeServiceAssertionWithRecipeWithTicker) ---"}}
FATAL  [2023-08-17 15:36:37] Failed To Stop ServicesFound 1 validation errors: Error while validating instruction stop_service(name="prelaunch-data-generator-cl-validator-keystore"). The instruction can be found at DEFAULT_PACKAGE_ID_FOR_SCRIPT[3:19]
	Caused by: There was an error validating 'stop_service' as service name 'prelaunch-data-generator-cl-validator-keystore' doesn't exist
 --- at /root/go/pkg/mod/github.com/kurtosis-tech/kurtosis/api/golang@v0.81.6/core/lib/enclaves/enclave_context.go:448 (getErrFromStarlarkRunResult) ---

**Comment by Mr-Nobody21** [comment]
@CyrusVorwald please share the version of DIVE cli that you are using  and also the version of kurtosis CLI that you are using .

**Comment by Mr-Nobody21** [comment]
@CyrusVorwald 

Please try once again with :-

- kurtosis Version:              0.81.8
- DIVE version                     0.0.7-beta

**Comment by CyrusVorwald** [comment]
This is with those versions.

❯ kurtosis version
CLI Version:              0.81.8
Running Engine Version:   0.81.8

❯ dive version
CLI version - v0.0.7-beta

**Comment by Mr-Nobody21** [comment]
Hi @CyrusVorwald 

this issue is fixed with the latest release v0.0.7 beta

closing this issue for now 

if the issue still persists on your end we will re-open the issue
